services:
  my-app:
    build: ./web-service
    ports:
      - "3000:3000"
    restart: always
    environment:
      - MONGO_DB_USERNAME=${MONGO_ADMIN_USER}
      - MONGO_DB_PASSWORD=${MONGO_ADMIN_PASS}
      - MONGO_URL=mongodb://${MONGO_ADMIN_USER}:${MONGO_ADMIN_PASS}@mongodb:27017/mydb?authSource=admin
      - REDIS_URL=redis://cache:6379
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - OTEL_SERVICE_NAME=web-service
    depends_on:
      mongodb:
        condition: service_healthy
      cache:
        condition: service_healthy
      otel-collector:
        condition: service_started
    networks:
      - app-net
      - observability-net

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PASS}
    volumes:
      - mongostorage:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--username", "${MONGO_ADMIN_USER}", "--password", "${MONGO_ADMIN_PASS}", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-net

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ADMIN_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ADMIN_PASS}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_ADMIN_USER}:${MONGO_ADMIN_PASS}@mongodb:27017/?authSource=admin
    depends_on:
      - "mongodb"
    networks:
      - app-net

  cache:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redisstorage:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-net

  worker:
    build: ./worker-service
    restart: always
    environment:
      - MONGO_DB_USERNAME=${MONGO_ADMIN_USER}
      - MONGO_DB_PASSWORD=${MONGO_ADMIN_PASS}
      - REDIS_URL=redis://cache:6379
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - OTEL_SERVICE_NAME=worker-service
    depends_on:
      mongodb:
        condition: service_healthy
      cache:
        condition: service_healthy
      otel-collector:
        condition: service_started
    networks:
      - app-net
      - observability-net

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-config.yaml"]
    volumes:
      - ./otel-config.yaml:/etc/otel-config.yaml
    ports:
      - "8889:8889" # Prometheus exporter metrics
    networks:
      - app-net
      - observability-net

networks:
  app-net:
  observability-net:
    external: true

volumes:
  mongostorage:
  redisstorage:
